ame: test_and_deploy

on:
  push:
  workflow_dispatch:
    inputs:
      deploy:
        description: "jouer un deploiment ?"
        required: false
        default: true
      test_add:
        description: "jouer un addition"
        required: false
        default: false
      test_sub:
        description: " jouer les tests de soustraction"
        required: false
      all_tests:
        description: "jouer tous les tests ?"
        required: false
        default: false
