name: test_and_deploy

on:
  push:
  workflow_dispatch:
    inputs:
      action:
        description: "que souhaitez vous jouer ?"
        required: false
        default: true
        type : choice
        options :
          - deploiment
          - addition
          - soustraction
          - deploiment
          - all_tests
        default : "deploiment"

jobs:
  test_add:
    runs-on: ubuntu-latest
    if: inputs.action == 'push' || input.action != 'soustraction' 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run test_add
        run: npm run test_add
        
  test_sub:
    runs-on: ubuntu-latest
    if: inputs.action == 'push' || input.action != 'addition' 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run test_sub
        run: npm run test_sub
  
  deploy:
    runs-on: ubuntu-latest
    needs: [test_add, test_sub]
    if: inputs.action == 'deploiment'
    steps:
      - name: Deployment
        run: echo "Déploiement"

  notify_failure:
    runs-on: ubuntu-latest
    needs : [deploy,test_sub,test_add]
    if: failure()
    steps:
      - name: Notify failure
        run: echo "Le déploiement echoue"
